version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tasktracker_postgres
    restart: always
    environment:
      POSTGRES_DB: tasktracker_db
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
